/**
 * @file Markdown reporter.
 *
 * The output is designed to be pasted straight into a GitHub issue, a pull
 * request comment, or a job summary (`$GITHUB_STEP_SUMMARY`). That constraint
 * drives every formatting decision: no ANSI, no HTML that GitHub strips, and
 * collapsible `<details>` blocks so a 30-check report does not bury a thread.
 *
 * @module report/markdown
 */

import { escapeMarkdownCell } from '../utils/format.js';
import { summarizeStatuses } from '../score.js';

/** Emoji used in Markdown, where ANSI colour is unavailable. */
const STATUS_EMOJI = { pass: '✅', warn: '⚠️', fail: '❌', error: '💥' };

/**
 * Render a scan result as Markdown.
 *
 * @param {import('../score.js').ScanResult} result The scan result.
 * @param {object} [options] Rendering options.
 * @param {boolean} [options.includeAllChecks=true] Include the full check table.
 * @param {boolean} [options.badge=true] Include a shields.io score badge.
 * @returns {string} Markdown document.
 */
export function renderMarkdownReport(result, { includeAllChecks = true, badge = true } = {}) {
  /** @type {string[]} */
  const out = [];
  const counts = summarizeStatuses(result);

  out.push(`# RepoRadar report — [${result.repository}](${result.url})`);
  out.push('');

  if (badge) {
    // shields.io colours must be URL-safe, so the leading # is stripped.
    const color = result.gradeColor.replace('#', '');
    out.push(
      `![RepoRadar score](https://img.shields.io/badge/RepoRadar-${result.score.toFixed(0)}%2F100%20${encodeURIComponent(result.grade)}-${color}?style=flat-square)`,
    );
    out.push('');
  }

  if (result.description) {
    out.push(`> ${result.description}`);
    out.push('');
  }

  out.push(
    `**Score: ${result.score.toFixed(1)} / 100 — ${result.grade} (${result.gradeLabel})**`,
  );
  out.push('');
  out.push(
    `${counts.pass} passed · ${counts.warn} warnings · ${counts.fail} failed` +
      (counts.error ? ` · ${counts.error} errors` : ''),
  );
  out.push('');

  // ── Dimension summary ─────────────────────────────────────────────────────
  out.push('## Dimensions');
  out.push('');
  out.push('| Dimension | Score | Bar | What it measures |');
  out.push('| :-- | --: | :-- | :-- |');
  for (const dimension of result.dimensions) {
    const filled = Math.round(dimension.ratio * 10);
    const bar = '█'.repeat(filled) + '░'.repeat(10 - filled);
    out.push(
      `| ${dimension.emoji} **${dimension.label}** ` +
        `| ${dimension.earned.toFixed(1)} / ${dimension.weight} ` +
        `| \`${bar}\` ` +
        `| ${escapeMarkdownCell(dimension.summary)} |`,
    );
  }
  out.push('');

  // ── Priority fixes ────────────────────────────────────────────────────────
  if (result.topFixes.length > 0) {
    out.push('## Fix these first');
    out.push('');
    out.push('Sorted by how many points each one recovers.');
    out.push('');
    result.topFixes.forEach((fix, index) => {
      out.push(`${index + 1}. **${fix.title}** — \`+${fix.lost.toFixed(1)} pts\``);
      out.push(`   - Current: ${escapeMarkdownCell(fix.message)}`);
      if (fix.hint) out.push(`   - Fix: ${escapeMarkdownCell(fix.hint)}`);
      if (fix.why) out.push(`   - Why it matters: ${escapeMarkdownCell(fix.why)}`);
      out.push('');
    });
  }

  // ── Full check table, collapsed ───────────────────────────────────────────
  if (includeAllChecks) {
    out.push('<details>');
    out.push(`<summary>All ${result.checks.length} checks</summary>`);
    out.push('');

    for (const dimension of result.dimensions) {
      out.push(`### ${dimension.emoji} ${dimension.label}`);
      out.push('');
      out.push('| | Check | Points | Result |');
      out.push('| :-: | :-- | --: | :-- |');
      for (const check of dimension.checks) {
        out.push(
          `| ${STATUS_EMOJI[check.status] ?? '❔'} ` +
            `| ${escapeMarkdownCell(check.title)} ` +
            `| ${check.earned.toFixed(1)} / ${check.weight} ` +
            `| ${escapeMarkdownCell(check.message)} |`,
        );
      }
      out.push('');
    }
    out.push('</details>');
    out.push('');
  }

  out.push('---');
  out.push('');
  out.push(
    `<sub>Generated by [RepoRadar](https://github.com/mornrain-lin/repo-radar) · ` +
      `${new Date(result.stats.scannedAt).toISOString().slice(0, 16).replace('T', ' ')} UTC</sub>`,
  );
  out.push('');

  return out.join('\n');
}
